# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_test_module.ipynb.

# %% auto 0
__all__ = ['TestModule', 'TestModule', 'TestModule']

# %% ../../nbs/02_test_module.ipynb 1
from ..module import *

# %% ../../nbs/03_module.ipynb 2
import unittest

class TestModule(unittest.TestCase):
   def test_foo(self): pass

# %% ../../nbs/03_module.ipynb 2
import unittest

class TestModule(unittest.TestCase):
   def test_foo(self): pass

# %% ../../nbs/03_module.ipynb 2
import unittest

class TestModule(unittest.TestCase):
   def test_foo(self): pass
